// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinhKhanhApi.Data;

#nullable disable

namespace VinhKhanhApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401093151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanhApi.Models.PoiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BanKinh")
                        .HasColumnType("float");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("MoTa_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa_Vi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa_Zh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFileAudio_Vi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UuTien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BanKinh = 50.0,
                            Lat = 10.76147422883112,
                            Lng = 106.70258525764435,
                            MoTa_En = "A long-standing famous seafood/snail restaurant on Vinh Khanh food street.",
                            MoTa_Vi = "Quán ốc nổi tiếng lâu năm trên phố ẩm thực Vĩnh Khánh.",
                            MoTa_Zh = "位于永庆美食街的知名老牌海鲜店。",
                            Ten = "Ốc Oanh",
                            UuTien = 1
                        },
                        new
                        {
                            Id = 2,
                            BanKinh = 65.0,
                            Lat = 10.76098,
                            Lng = 106.70342,
                            MoTa_En = "A popular seafood spot on Vinh Khanh street.",
                            MoTa_Vi = "Quán ốc đông khách trên đường Vĩnh Khánh.",
                            MoTa_Zh = "永庆街上的人气海鲜店。",
                            Ten = "Ốc Thảo",
                            UuTien = 2
                        },
                        new
                        {
                            Id = 3,
                            BanKinh = 65.0,
                            Lat = 10.76076,
                            Lng = 106.70368,
                            MoTa_En = "A late-night seafood place in Vinh Khanh food area.",
                            MoTa_Vi = "Quán ốc mở khuya trong khu ẩm thực Vĩnh Khánh.",
                            MoTa_Zh = "永庆美食区内营业到深夜的海鲜店。",
                            Ten = "Ốc Vũ",
                            UuTien = 3
                        },
                        new
                        {
                            Id = 4,
                            BanKinh = 65.0,
                            Lat = 10.76042,
                            Lng = 106.70408,
                            MoTa_En = "A familiar seafood eatery for locals.",
                            MoTa_Vi = "Quán ốc quen thuộc với thực khách địa phương.",
                            MoTa_Zh = "本地食客常去的海鲜店。",
                            Ten = "Ốc Phát",
                            UuTien = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
