// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinhKhanhApi.Data;

#nullable disable

namespace VinhKhanhApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanhApi.Models.PoiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BanKinh")
                        .HasColumnType("float");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("MoTa_En")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa_Vi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa_Zh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFileAudio_Vi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFileAudio_En")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenFileAudio_Zh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UuTien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BanKinh = 50.0,
                            Lat = 10.756500000000001,
                            Lng = 106.6896,
                            MoTa_En = "Famous bun bo Hue restaurant with 30-year history.",
                            MoTa_Vi = "Quán bún bò nổi tiếng với hơn 30 năm lịch sử.",
                            MoTa_Zh = "著名的顺化牛肉米线餐厅，拥有30年历史。",
                            Ten = "Quán Bún Bò Huế Vĩnh Khánh",
                            UuTien = 1
                        },
                        new
                        {
                            Id = 2,
                            BanKinh = 80.0,
                            Lat = 10.757999999999999,
                            Lng = 106.691,
                            MoTa_En = "Traditional market of District 4.",
                            MoTa_Vi = "Khu chợ truyền thống lâu đời của quận 4.",
                            MoTa_Zh = "第四郡传统市场。",
                            Ten = "Chợ Xóm Chiếu",
                            UuTien = 2
                        });
                });

            modelBuilder.Entity("VinhKhanhApi.Models.PlaybackLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nguon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoiId")
                        .HasColumnType("int");

                    b.Property<string>("PoiTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianNghe")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiLuongGiay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlaybackLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
